"""Add cascade delete to foreign keys

Revision ID: 7b3e2e877a4f
Revises: bcbef7a472a1
Create Date: 2026-09-23 06:37:12.758077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3e2e877a4f'
down_revision: Union[str, Sequence[str], None] = 'bcbef7a472a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commercialitems_type_id_fkey'), 'commercialitems', type_='foreignkey')
    op.create_foreign_key(None, 'commercialitems', 'commercialtype', ['type_id'], ['type_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'commercialitems', type_='foreignkey')
    op.create_foreign_key(op.f('commercialitems_type_id_fkey'), 'commercialitems', 'commercialtype', ['type_id'], ['type_id'])
    # ### end Alembic commands ###
