"""Add cascade delete to foreign keys

Revision ID: 8884409742fc
Revises: 7b3e2e877a4f
Create Date: 2026-09-23 06:37:47.442866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8884409742fc'
down_revision: Union[str, Sequence[str], None] = '7b3e2e877a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('adminaccess_admin_id_fkey'), 'adminaccess', type_='foreignkey')
    op.create_foreign_key(None, 'adminaccess', 'admin', ['admin_id'], ['admin_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orderdelivery_order_id_fkey'), 'orderdelivery', type_='foreignkey')
    op.create_foreign_key(None, 'orderdelivery', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('orderitems_item_id_fkey'), 'orderitems', type_='foreignkey')
    op.drop_constraint(op.f('orderitems_order_id_fkey'), 'orderitems', type_='foreignkey')
    op.create_foreign_key(None, 'orderitems', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orderitems', 'commercialitems', ['item_id'], ['item_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'orderitems', type_='foreignkey')
    op.create_foreign_key(op.f('orderitems_order_id_fkey'), 'orderitems', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key(op.f('orderitems_item_id_fkey'), 'orderitems', 'commercialitems', ['item_id'], ['item_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'orderdelivery', type_='foreignkey')
    op.create_foreign_key(op.f('orderdelivery_order_id_fkey'), 'orderdelivery', 'orders', ['order_id'], ['order_id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'adminaccess', type_='foreignkey')
    op.create_foreign_key(op.f('adminaccess_admin_id_fkey'), 'adminaccess', 'admin', ['admin_id'], ['admin_id'])
    # ### end Alembic commands ###
