"""Add set null on delete to promotional id foreign key

Revision ID: 9f2f06eafa38
Revises: 8884409742fc
Create Date: 2026-09-23 10:21:08.345802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2f06eafa38'
down_revision: Union[str, Sequence[str], None] = '8884409742fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('commercialitems_promotional_id_fkey'), 'commercialitems', type_='foreignkey')
    op.create_foreign_key(None, 'commercialitems', 'promotions', ['promotional_id'], ['promotional_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'commercialitems', type_='foreignkey')
    op.create_foreign_key(op.f('commercialitems_promotional_id_fkey'), 'commercialitems', 'promotions', ['promotional_id'], ['promotional_id'])
    # ### end Alembic commands ###
