"""Adding constraints and fixing somethings

Revision ID: bcbef7a472a1
Revises: bb9b0c30f12f
Create Date: 2026-09-23 05:54:53.568605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbef7a472a1'
down_revision: Union[str, Sequence[str], None] = 'bb9b0c30f12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'commercialtype', ['type_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'commercialtype', type_='unique')
    # ### end Alembic commands ###
